services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: vault
      POSTGRES_USER: vault
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-vaultpass}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    restart: unless-stopped

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER:-admin}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD:-admin12345}
    volumes:
      - miniodata:/data
    ports:
      - "9001:9001"   # web console
    restart: unless-stopped

  kafka:
    image: apache/kafka:3.8.0
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    restart: unless-stopped

  app:
    build: ./app
    environment:
      DATABASE_URL: postgresql://vault:${POSTGRES_PASSWORD:-vaultpass}@postgres:5432/vault
      REDIS_HOST: redis
      MINIO_ENDPOINT: minio:9000
      MINIO_USER: ${MINIO_USER:-admin}
      MINIO_PASSWORD: ${MINIO_PASSWORD:-admin12345}
      KAFKA_BROKER: kafka:9092
    depends_on: [postgres, redis, minio, kafka]
    restart: unless-stopped

  worker:
    build: ./app
    command: python worker.py
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on: [kafka]
    restart: unless-stopped

  nginx:
    image: nginx:1.27
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on: [app]
    restart: unless-stopped

volumes:
  pgdata:
  miniodata:
